#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_ref() {
  local file="$1" ref="$2"
  grep -Fq -- "$ref" "$ROOT/$file" || {
    echo "missing reference '$ref' in $file" >&2
    exit 1
  }
}

reject_ref() {
  local file="$1" ref="$2"
  if grep -Fq -- "$ref" "$ROOT/$file"; then
    echo "obsolete reference '$ref' in $file" >&2
    exit 1
  fi
}

for ref in \
  "references/academic-workflow.md" \
  "references/academic-templates.md" \
  "references/academic-schema-contract.md" \
  "references/academicforge-skill-catalog.md"
do
  require_ref "SKILL.md" "$ref"
  require_ref "references/xflow-map.md" "$ref"
done

require_ref "SKILL.md" "PowerShell Native Command Safety"
require_ref "SKILL.md" "Windows users should default to PowerShell plus Python devctl"
require_ref "SKILL.md" "WSL is a developer compatibility path"
require_ref "SKILL.md" "Invoke-XFlowGit -GitArguments @(...)"
require_ref "SKILL.md" "AI Rule Entrypoint Safety"
require_ref "SKILL.md" "devctl rules sync <id>"
require_ref "SKILL.md" "templates/ai-rules.json"
require_ref "SKILL.md" 'Legacy `_ops` Migration Safety'
require_ref "SKILL.md" "devctl migrate inspect"
require_ref "SKILL.md" "devctl migrate wrappers"
require_ref "SKILL.md" "python -m xflow"
require_ref "SKILL.md" "Review-Only Scope Safety"
require_ref "SKILL.md" "devctl check scope --issue <id> --mode review-only"
require_ref "SKILL.md" ".xflow/scope-policy.json"
require_ref "SKILL.md" "Approval And PR Sealing Safety"
require_ref "SKILL.md" "devctl approval prepare --issue <id> --action <action> --file <artifact>"
require_ref "SKILL.md" "devctl check current-task --issue <id>"
require_ref ".gitignore" "__pycache__/"
require_ref ".gitignore" "*.py[cod]"
require_ref ".gitignore" ".pytest_cache/"
require_ref ".gitignore" "*.tmp"
require_ref "templates/ai-rules.json" '"schema": "academic-xflow/ai-rules/v1"'
require_ref "templates/ai-rules.json" '"id": "codex"'
require_ref "templates/ai-rules.json" '"target": "AGENTS.md"'
require_ref "templates/ai-rules.json" '"template": "codex-agents.academic.md"'
require_ref "templates/ai-rules.json" '"id": "cursor"'
require_ref "templates/ai-rules.json" '"target": ".cursorrules"'
require_ref "templates/ai-rules.json" '"template": "cursorrules.academic"'
require_ref "templates/codex-agents.academic.md" "devctl rules list"
require_ref "templates/codex-agents.academic.md" "devctl rules sync <id>"
require_ref "templates/codex-agents.academic.md" "Default to PowerShell plus Python devctl on Windows"
require_ref "templates/codex-agents.academic.md" "Do not switch to WSL"
require_ref "templates/codex-agents.academic.md" "devctl migrate inspect"
require_ref "templates/codex-agents.academic.md" "devctl migrate wrappers"
require_ref "templates/codex-agents.academic.md" "python -m xflow"
require_ref "templates/codex-agents.academic.md" "must not call Bash, WSL, Claude, AcademicForge, or any installer"
require_ref "templates/codex-agents.academic.md" "Do not invent active approval filenames"
require_ref "templates/codex-agents.academic.md" "Do not add AI-client co-author trailers"
require_ref "templates/codex-agents.academic.md" "devctl check scope --issue <id> --mode review-only"
require_ref "templates/codex-agents.academic.md" "devctl approval prepare --issue <id> --action <action> --file <artifact>"
require_ref "templates/codex-agents.academic.md" "devctl check current-task --issue <id>"
require_ref "templates/cursorrules.academic" "devctl claude doctor"
require_ref "templates/cursorrules.academic" "Default to PowerShell plus Python devctl on Windows"
require_ref "templates/cursorrules.academic" "Do not switch to WSL"
require_ref "templates/cursorrules.academic" "devctl claude run --issue <id>"
require_ref "templates/cursorrules.academic" "devctl claude skills"
require_ref "templates/cursorrules.academic" "devctl rules list"
require_ref "templates/cursorrules.academic" "devctl rules sync <id>"
require_ref "templates/cursorrules.academic" "devctl migrate inspect"
require_ref "templates/cursorrules.academic" "devctl migrate wrappers"
require_ref "templates/cursorrules.academic" "python -m xflow"
require_ref "templates/cursorrules.academic" "must not call Bash, WSL, Claude, AcademicForge, or any installer"
require_ref "templates/cursorrules.academic" "academicforge-skill-catalog.md"
require_ref "templates/cursorrules.academic" 'checked `.claude/skills` roots'
require_ref "templates/cursorrules.academic" "Claude Skill:"
require_ref "templates/cursorrules.academic" "Invocation:"
require_ref "templates/cursorrules.academic" "/peer-review"
require_ref "templates/cursorrules.academic" "DEVCTL_CLAUDE_ARGS"
require_ref "templates/cursorrules.academic" "focus=methodology severity=major"
require_ref "templates/cursorrules.academic" "successful CLI exit code alone is not enough"
require_ref "templates/cursorrules.academic" "generic reply asking"
require_ref "templates/cursorrules.academic" 'Claude-resolvable flat skill directory'
require_ref "templates/cursorrules.academic" 'nested official source path'
require_ref "templates/cursorrules.academic" "--body-file"
require_ref "templates/cursorrules.academic" "fetch, pin reviewed SHA, test, human review, then commit"
require_ref "templates/cursorrules.academic" 'Do not pipe native Git commands through `2>&1 | Out-String`'
require_ref "templates/cursorrules.academic" '$LASTEXITCODE'
require_ref "templates/cursorrules.academic" ".xflow/tools/xflow-powershell-native.ps1"
require_ref "templates/cursorrules.academic" "Do not combine multiple native commands in one PowerShell line"
require_ref "templates/cursorrules.academic" "PowerShell check scripts must use ASCII terminal output"
require_ref "templates/cursorrules.academic" "Initialize-XFlowPowerShellEncoding"
require_ref "templates/cursorrules.academic" "Write-XFlowStatus"
require_ref "templates/cursorrules.academic" "Git-facing text only"
require_ref "templates/cursorrules.academic" "commit messages, remote Issue titles/bodies, and MR/PR"
require_ref "templates/cursorrules.academic" "titles/bodies should follow the user's language"
require_ref "templates/cursorrules.academic" "Chinese, use Chinese as the primary language"
require_ref "templates/cursorrules.academic" "apply to non-Git artifacts"
require_ref "templates/cursorrules.academic" "Do not add Cursor co-author trailers"
require_ref "templates/cursorrules.academic" "Co-authored-by: Cursor <cursoragent@cursor.com>"
require_ref "templates/cursorrules.academic" "git commit --trailer"
require_ref "templates/cursorrules.academic" "ignore = untracked"
require_ref "templates/cursorrules.academic" "devctl check submodule-hygiene"
require_ref "templates/cursorrules.academic" "Workflow Product Line"
require_ref "templates/cursorrules.academic" "Paper Base Branch"
require_ref "templates/cursorrules.academic" "Task Branch"
require_ref "templates/cursorrules.academic" "Remote-published body files"
require_ref "templates/cursorrules.academic" "<!-- xflow:"
require_ref "templates/cursorrules.academic" "Do not invent active approval filenames"
require_ref "templates/cursorrules.academic" "After the PR is merged, seal the task board"
require_ref "templates/cursorrules.academic" "Approved Action: git-mr"
require_ref "templates/cursorrules.academic" "devctl approval prepare --issue <id> --action <action> --file <artifact>"
require_ref "templates/cursorrules.academic" "devctl check current-task --issue <id>"
require_ref "templates/cursorrules.academic" 'Do not create or push an `academic` branch in the paper repository'
require_ref "templates/cursorrules.academic" "devctl check scope --issue <id> --mode review-only"
require_ref "templates/xflow-powershell-native.ps1" "function Invoke-XFlowNative"
require_ref "templates/xflow-powershell-native.ps1" "function Invoke-XFlowGit"
require_ref "templates/xflow-powershell-native.ps1" "function Initialize-XFlowPowerShellEncoding"
require_ref "templates/xflow-powershell-native.ps1" "function Write-XFlowStatus"
require_ref "templates/xflow-powershell-native.ps1" "GitArguments"
require_ref "templates/xflow-powershell-native.ps1" "Start-Process"
require_ref "templates/xflow-powershell-native.ps1" "ExitCode"
require_ref "references/academic-workflow.md" "templates/ai-rules.json"
require_ref "references/academic-workflow.md" "devctl rules list"
require_ref "references/academic-workflow.md" "devctl rules sync cursor"
require_ref "references/academic-workflow.md" "AGENTS.md"
require_ref "references/academic-workflow.md" "templates/xflow-powershell-native.ps1"
require_ref "references/academic-workflow.md" "academicforge-skill-catalog.md"
require_ref "references/academic-workflow.md" "Invocation: /<skill-name>"
require_ref "references/academic-workflow.md" "DEVCTL_CLAUDE_ARGS"
require_ref "references/academic-workflow.md" "the whole invocation line"
require_ref "references/academic-workflow.md" "devctl claude skills"
require_ref "references/academic-workflow.md" "rejects empty output"
require_ref "references/academic-workflow.md" "does not hard-code one academic"
require_ref "references/academic-workflow.md" "checked skill roots"
require_ref "references/academic-workflow.md" 'flat skill directories'
require_ref "references/academic-workflow.md" 'callable as `/peer-review`'
require_ref "references/academic-workflow.md" "Already-initialized paper repositories must not silently track the latest"
require_ref "references/academic-workflow.md" "manuscript/"
require_ref "references/academic-workflow.md" "assets/"
require_ref "references/academic-workflow.md" ".xflow/ops/devctl"
require_ref "references/academic-workflow.md" ".xflow/ops/workflow"
require_ref "references/academic-workflow.md" ".xflow/issues/issue-<id>/"
require_ref "references/academic-workflow.md" ".xflow/local/"
require_ref "references/academic-workflow.md" "git -C .xflow/ops/devctl fetch origin academic"
require_ref "references/academic-workflow.md" "pin reviewed SHA"
require_ref "references/academic-workflow.md" "commit the submodule pointer"
require_ref "references/academic-workflow.md" "ignore = untracked"
require_ref "references/academic-workflow.md" "devctl check submodule-hygiene"
require_ref "references/academic-workflow.md" "PowerShell Native Git Rule"
require_ref "references/academic-workflow.md" "Windows users should default to PowerShell plus Python devctl"
require_ref "references/academic-workflow.md" "WSL is a developer compatibility path"
require_ref "references/academic-workflow.md" "GitHub Issue And PR Provider"
require_ref "references/academic-workflow.md" "GITHUB_TOKEN"
require_ref "references/academic-workflow.md" "devctl git mr --title"
require_ref "references/academic-workflow.md" "devctl issue list --state open --limit 20"
require_ref "references/academic-workflow.md" "devctl issue comment <id> --body-file"
require_ref "references/academic-workflow.md" "devctl git pr-get <number>"
require_ref "references/academic-workflow.md" "devctl approval prepare --issue <id> --action <action> --file <reviewed-artifact>"
require_ref "references/academic-workflow.md" "state-update-suggestion.md"
require_ref "references/academic-workflow.md" 'Do not use `2>&1 | Out-String` for `git submodule add`, `git clone`, `git fetch`, or `git checkout`'
require_ref "references/academic-workflow.md" "Do not combine multiple native commands in one PowerShell line"
require_ref "references/academic-workflow.md" "Branch Semantics Rule"
require_ref "references/academic-workflow.md" "<!-- workflow-product-line: academic -->"
require_ref "references/academic-workflow.md" "<!-- paper-base-branch:"
require_ref "references/academic-workflow.md" "<!-- task-branch:"
require_ref "references/academic-workflow.md" "Approved Action: git-mr"
require_ref "references/academic-workflow.md" "After the PR is merged, the task is sealed"
require_ref "references/academic-workflow.md" "Do not invent active approval filenames"
require_ref "references/academic-workflow.md" "Remote-published body files"
require_ref "references/academic-workflow.md" "review-only"
require_ref "references/academic-workflow.md" 'Legacy `_ops` Migration'
require_ref "references/academic-workflow.md" "devctl migrate inspect"
require_ref "references/academic-workflow.md" "devctl migrate wrappers"
require_ref "references/academic-workflow.md" "python -m xflow"
require_ref "references/academic-workflow.md" "must not call Bash, WSL, Claude, or any installer"
require_ref "references/academic-workflow.md" ".xflow/issues/issue-<id>/**"
require_ref "references/academic-workflow.md" ".xflow/local/**"
require_ref "references/academic-workflow.md" ".xflow/scope-policy.json"
require_ref "references/academic-workflow.md" "protected hints"
require_ref "references/academic-schema-contract.md" "templates/ai-rules.json"
require_ref "references/academic-schema-contract.md" "devctl rules list"
require_ref "references/academic-schema-contract.md" "devctl rules sync <id>"
require_ref "references/academic-schema-contract.md" "codex -> AGENTS.md"
require_ref "references/academic-schema-contract.md" "cursor -> .cursorrules"
require_ref "references/academic-schema-contract.md" "must not overwrite an existing different file"
require_ref "references/academic-schema-contract.md" "academicforge-skill-catalog.md"
require_ref "references/academic-schema-contract.md" "AcademicForge Skill:"
require_ref "references/academic-schema-contract.md" "devctl claude skills"
require_ref "references/academic-schema-contract.md" "may include skill arguments"
require_ref "references/academic-schema-contract.md" "preserve the complete invocation line"
require_ref "references/academic-schema-contract.md" "A zero exit"
require_ref "references/academic-schema-contract.md" "must not hard-code one academic output format"
require_ref "references/academic-schema-contract.md" "validation alone is not enough"
require_ref "references/academic-schema-contract.md" "checked skill roots"
require_ref "references/academic-schema-contract.md" "Claude-resolvable flat"
require_ref "references/academic-schema-contract.md" "Pinned Update Contract"
require_ref "references/academic-schema-contract.md" "fetch -> pin reviewed SHA -> test -> human review -> commit"
require_ref "references/academic-schema-contract.md" "PowerShell Native Command Contract"
require_ref "references/academic-schema-contract.md" "Windows academic operation must not require WSL"
require_ref "references/academic-schema-contract.md" "A native Git command is failed only when its process exit code is non-zero"
require_ref "references/academic-schema-contract.md" "Legacy Layout Migration Contract"
require_ref "references/academic-schema-contract.md" "devctl migrate inspect"
require_ref "references/academic-schema-contract.md" "devctl migrate wrappers"
require_ref "references/academic-schema-contract.md" "python -m xflow"
require_ref "references/academic-schema-contract.md" "must not call Bash, WSL, Claude, AcademicForge, or any installer"
require_ref "references/academic-schema-contract.md" "PowerShell helper template"
require_ref "references/academic-schema-contract.md" "native command composition"
require_ref "references/academic-schema-contract.md" "Submodule Hygiene Contract"
require_ref "references/academic-schema-contract.md" "devctl check submodule-hygiene"
require_ref "references/academic-schema-contract.md" ".xflow/ops/devctl"
require_ref "references/academic-schema-contract.md" ".xflow/ops/workflow"
require_ref "references/academic-schema-contract.md" ".xflow/issues/issue-<id>/"
require_ref "references/academic-schema-contract.md" "Branch Semantics Contract"
require_ref "references/academic-schema-contract.md" "GitHub Issue And PR Provider Contract"
require_ref "references/academic-schema-contract.md" '`devctl git mr` in academic Python mode must'
require_ref "references/academic-schema-contract.md" '`devctl issue list` and `devctl issue show` in academic Python mode must'
require_ref "references/academic-schema-contract.md" '`devctl issue comment` in academic Python mode must'
require_ref "references/academic-schema-contract.md" '`devctl issue close` in academic Python mode must'
require_ref "references/academic-schema-contract.md" '`devctl git pr-get` in academic Python mode must'
require_ref "references/academic-schema-contract.md" "metadata writeback must not require a second approval"
require_ref "references/academic-schema-contract.md" "the task is sealed"
require_ref "references/academic-schema-contract.md" "devctl check scope --issue <id> --mode review-only"
require_ref "references/academic-schema-contract.md" "devctl approval prepare --issue <id> --action <action> --file <artifact>"
require_ref "references/academic-schema-contract.md" "devctl check current-task --issue <id>"
require_ref "references/academic-schema-contract.md" "devctl.pr-url"
require_ref "references/academic-schema-contract.md" ".xflow/scope-policy.json"
require_ref "references/academic-schema-contract.md" "allowlist"
require_ref "references/academic-schema-contract.md" "<!-- xflow: academic-mr-draft -->"
require_ref "references/academic-schema-contract.md" "<!-- xflow: academic-issue-draft -->"
require_ref "templates/cursorrules.academic" "For GitHub PR creation"
require_ref "templates/cursorrules.academic" 'devctl git mr --title "<title>" --body-file <file> --base <paper-base> --issue <id>'
require_ref "templates/cursorrules.academic" "For GitHub Issue list/show"
require_ref "templates/cursorrules.academic" "devctl issue comment <id> --body-file <file>"
require_ref "templates/cursorrules.academic" "For GitHub PR lookup"
require_ref "references/academic-schema-contract.md" 'If `XFLOW_PLATFORM=gitee`, the Python academic provider must fail closed'
require_ref "references/academic-schema-contract.md" '`Target Branch: academic` is invalid'
require_ref "references/academic-templates.md" "<!-- xflow: academic-issue-draft -->"
require_ref "references/academic-templates.md" "<!-- xflow: academic-mr-draft -->"
require_ref "references/academic-templates.md" "Claude Skill:"
require_ref "references/academic-templates.md" "Skill Source:"
require_ref "references/academic-templates.md" "Invocation:"
require_ref "references/academic-templates.md" "optional skill arguments"
require_ref "references/academic-templates.md" "Return Markdown with these exact section headings:"
require_ref "references/academic-templates.md" "## Proposed Changes"
require_ref "references/academicforge-skill-catalog.md" "/peer-review"
require_ref "references/academicforge-skill-catalog.md" "/ppw-reviewer-simulation"
require_ref "references/academicforge-skill-catalog.md" 'Scanned `SKILL.md` files: 274'
require_ref "references/academic-templates.md" "<!-- workflow-product-line: academic -->"
require_ref "references/academic-templates.md" "<!-- paper-base-branch: <main|master|user-defined> -->"
require_ref "references/academic-templates.md" "<!-- task-branch: <feature/<issue>-<slug>|review/<issue>-<slug>|chore/update-academic-xflow-<date>> -->"
require_ref "references/academic-templates.md" "## Review Request"
require_ref "references/academic-templates.md" "Do not create alternate"
require_ref "references/academic-templates.md" "Approved: no"
require_ref "references/academic-templates.md" "## Suggested Command"
require_ref "references/academic-templates.md" "## .xflow/current-task.md"
require_ref "references/academic-templates.md" "State Update Suggestion:"
require_ref "SKILL.md" "Approval And PR Sealing Safety"
require_ref "SKILL.md" "After the PR is merged, seal the task board"
require_ref "SKILL.md" "Remote Published Body Safety"

reject_ref "references/academic-templates.md" "Target Branch: academic"
reject_ref "references/academic-templates.md" "# Academic Issue Draft"
reject_ref "references/academic-templates.md" "# MR Draft"
reject_ref "references/academic-templates.md" "AcademicForge Skill:"
reject_ref "references/academic-workflow.md" "claude mcp add academicforge"
reject_ref "templates/cursorrules.academic" "claude mcp add academicforge"
reject_ref "templates/cursorrules.academic" "Target Branch: academic"
reject_ref "references/academic-templates.md" ".xflow/issue-<id>/"
reject_ref "templates/cursorrules.academic" 'local-review-mr.md` as the active'

echo "academic entrypoint ok"
